codecov:
  max_report_age: off
  notify:
    after_n_builds: 2
  require_ci_to_pass: false

coverage:
  status:
    project:
      default:
        threshold: 1
    patch:
      default:
        threshold: 10
