version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  reviewers:
  - frett
  assignees:
  - frett
  ignore:
  - dependency-name: com.squareup.okhttp3:mockwebserver
    versions:
    - ">= 3.13.a"
    - "< 3.14"
  - dependency-name: com.squareup.okhttp3:mockwebserver
    versions:
    - ">= 3.14.a"
    - "< 3.15"
  - dependency-name: com.squareup.okhttp3:mockwebserver
    versions:
    - ">= 4.a"
    - "< 5"
  - dependency-name: com.squareup.okhttp3:okhttp
    versions:
    - ">= 3.13.a"
    - "< 3.14"
  - dependency-name: com.squareup.okhttp3:okhttp
    versions:
    - ">= 3.14.a"
    - "< 3.15"
  - dependency-name: com.squareup.okhttp3:okhttp
    versions:
    - ">= 4.a"
    - "< 5"
  - dependency-name: com.squareup.retrofit2:retrofit
    versions:
    - ">= 2.7.a"
    - "< 2.8"
  - dependency-name: com.squareup.retrofit2:retrofit
    versions:
    - ">= 2.8.a"
    - "< 2.9"
  - dependency-name: com.squareup.retrofit2:retrofit
    versions:
    - ">= 2.9.a"
    - "< 2.10"
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-core
    versions:
    - ">= 1.3.6-mpp-dev-6.a"
    - "< 1.3.7"
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-core
    versions:
    - ">= 1.3.9-native-mt-2.a"
    - "< 1.3.10"
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-core
    versions:
    - ">= 1.3.9-native-mt.a"
    - "< 1.3.10"
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-test
    versions:
    - ">= 1.3.9-native-mt-2.a"
    - "< 1.3.10"
