version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  reviewers:
  - frett
  assignees:
  - frett
  ignore:
  - dependency-name: com.squareup.okhttp3:mockwebserver
    versions:
    - ">= 3.13.a"
  - dependency-name: com.squareup.okhttp3:okhttp
    versions:
    - ">= 3.13.a"
  - dependency-name: com.squareup.picasso:picasso
    versions:
    - "= 2.71828"
  - dependency-name: com.squareup.retrofit2:retrofit
    versions:
    - ">= 2.7.a"
#  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-core
#    versions:
#    - ">= 1.3.9-native-mt.a"
#    - "< 1.3.10"
