language: android
dist: trusty
sudo: required
jdk: oraclejdk8
env:
  global:
    - GRADLE_OPTS="-Xms128m -Xmx3072m -Dorg.gradle.jvmargs='-Xms128m'"
    - DEPLOY_USERNAME=travis-ci-android-gto-support
    # DEPLOY_PASSWORD={password}
    - secure: "eswtL3VDqa+k8U3TivAXo9B90qG09fHAdnagLe/efD7d9y/CrrYn6PrDhDx29A4+mrenbuOw2WDtneN5mmZ/CxVvYA4ILUNbhK5DlOiqxxPosfNISJumC6sn2+nSpJcR59tvxwRhLuupbQzTfTyliPoTMj7T9OQQQQ4BnaEGvb4="
branches:
  only:
  - master
  - /^v\d+(\.\d+){1,}$/

stages:
- test
- name: deploy
  if: type = push AND (branch = master OR tag =~ /^v\d+(\.\d+){1,}$/)

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.android/build-cache
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

before_install:
# Install SDK license so Android Gradle plugin can install deps.
- mkdir "$ANDROID_HOME/licenses" || true
- echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> "$ANDROID_HOME/licenses/android-sdk-license"
- echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> "$ANDROID_HOME/licenses/android-sdk-license"

jobs:
  fast_finish: true
  include:
  - name: "Build"
    stage: test

    install: skip
    script: ./gradlew clean assemble --continue --stacktrace --parallel

  - name: "Static Analysis"
    stage: test

    install: skip
    script: ./gradlew check -x test --continue --stacktrace --parallel

  - name: "Unit Tests"
    stage: test

    install: skip
    script: ./gradlew test jacocoTestReport --continue --stacktrace --parallel --max-workers 2

    after_success:
    - bash <(curl -s https://codecov.io/bash)

  - name: "Release"
    stage: deploy

    install:
    - echo cruGlobalMavenRepositoryUsername=$DEPLOY_USERNAME >> $HOME/.gradle/gradle.properties
    - echo cruGlobalMavenRepositoryPassword=$DEPLOY_PASSWORD >> $HOME/.gradle/gradle.properties
    script: skip

    deploy:
      provider: script
      skip_cleanup: true
      script: ./gradlew publish --parallel
      on:
        repo: CruGlobal/android-gto-support
        all_branches: true
        jdk: oraclejdk8

notifications:
  email: false
