name: Build GTO-Support

on:
  push:
    branches: [master]
    tags: ['v[0-9]+*']
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ORG_GRADLE_PROJECT_releaseBuild: ${{ github.event_name == 'push' && contains(github.ref, 'refs/tags/') }}
  ORG_GRADLE_PROJECT_versionSuffix: ${{ (github.event_name == 'pull_request' && format('PR{0}', github.event.pull_request.number)) || '' }}

jobs:
  build:
    name: Build Library
    runs-on: macos-11
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache Konan
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ github.sha }}
          restore-keys: ${{ runner.os }}-konan-
      - name: Setup Java JDK
        uses: actions/setup-java@v3.7.0
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Build Library
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble --scan

  checkstyle:
    name: Checkstyle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache Konan
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ github.sha }}
          restore-keys: ${{ runner.os }}-konan-
      - name: Run Checkstyle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: checkstyle --scan
      - name: Archive Checkstyle results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: checkstyle-results
          path: "**/build/reports/checkstyle/"

  ktlint:
    name: ktlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache Konan
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ github.sha }}
          restore-keys: ${{ runner.os }}-konan-
      - name: Run ktlint
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ktlintCheck --scan
      - name: Archive ktlint results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ktlint-results
          path: "**/build/reports/ktlint/"

  lint:
    name: Lint Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache Konan
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ github.sha }}
          restore-keys: ${{ runner.os }}-konan-
      - name: Run Lint Checks
        uses: gradle/gradle-build-action@v2
        with:
          arguments: lint --scan
      - name: Archive lint results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: lint-results
          path: "**/build/reports/lint-results*.*"

  android_tests:
    name: Android Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache Konan
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ github.sha }}
          restore-keys: ${{ runner.os }}-konan-
      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run Unit Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test koverMergedXmlReport --scan
      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
      - name: Archive Unit Test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: android-unit-test-results
          path: "**/build/reports/tests/"
      - name: Archive kover results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: android-kover-results
          path: "**/build/reports/kover/"

  ios_tests:
    name: iOS Unit Tests
    runs-on: macos-11
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache Konan
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ github.sha }}
          restore-keys: ${{ runner.os }}-konan-
      - name: Setup Java JDK
        uses: actions/setup-java@v3.7.0
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Run iOS Unit Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: iosX64Test iosX64BackgroundTest --scan

  js_tests:
    name: JS Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache Konan
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ github.sha }}
          restore-keys: ${{ runner.os }}-konan-
      - name: Run JS Unit Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jsIrTest jsLegacyTest --scan
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: js-unit-test-results
          path: "**/build/reports/tests/"

  deploy:
    name: Deploy Library
    runs-on: macos-11
    if: >-
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'schedule' ||
      github.event_name == 'pull_request' ||
      (github.event_name == 'push' && (github.ref == 'refs/heads/master' || contains(github.ref, 'refs/tags/')))
    needs: [build, checkstyle, ktlint, lint, android_tests, ios_tests, js_tests]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache Konan
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ github.sha }}
          restore-keys: ${{ runner.os }}-konan-
      - name: Setup Java JDK
        uses: actions/setup-java@v3.7.0
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Publish library
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish --scan
        env:
          ORG_GRADLE_PROJECT_cruGlobalMavenRepositoryUsername: ${{ secrets.DEPLOY_USERNAME }}
          ORG_GRADLE_PROJECT_cruGlobalMavenRepositoryPassword: ${{ secrets.DEPLOY_PASSWORD }}
