name: Build GTO-Support

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ORG_GRADLE_PROJECT_releaseBuild: ${{ github.event_name == 'push' && contains(github.ref, 'refs/tags/') }}
  ORG_GRADLE_PROJECT_versionSuffix: ${{ (github.event_name == 'pull_request' && format('PR{0}', github.event.pull_request.number)) || '' }}

jobs:
  static:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Static Analysis
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble check -x test --continue --stacktrace
      - name: Archive ktlint results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ktlint-results
          path: "**/build/reports/ktlint/"
      - name: Archive lint results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: lint-results
          path: "**/build/reports/lint-results*.*"

  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run Unit Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test koverMergedXmlReport --continue --stacktrace
      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          verbose: true
      - name: Archive Unit Test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-results
          path: "**/build/reports/tests/"

  deploy:
    name: Deploy Library
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && (github.ref == 'refs/heads/master' || contains(github.ref, 'refs/tags/')))
    needs: [static, tests]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Publish library
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          ORG_GRADLE_PROJECT_cruGlobalMavenRepositoryUsername: ${{ secrets.DEPLOY_USERNAME }}
          ORG_GRADLE_PROJECT_cruGlobalMavenRepositoryPassword: ${{ secrets.DEPLOY_PASSWORD }}
